name: Test

on: [ push ]

jobs:
  test:
    name: Test - php${{ matrix.php }} - symfony:${{ matrix.symfony-version }}
    runs-on: ubuntu-20.04
    env:
      SYMFONY_REQUIRE: ${{ matrix.symfony-version }}
    strategy:
      matrix:
        php:
          - '8.2'
        symfony-version:
          - "~6.4"
          - "~7.1"

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          ini-values: memory_limit=-1
          tools: composer

      - name: Get Composer Cache Directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-${{ matrix.php }}

      - name: Composer selfupdate
        run: composer selfupdate

      - name: Require symfony/framework-bundle
        run: composer require symfony/framework-bundle:${{ matrix.symfony-version }}

      - name: Run phpunit
        run: vendor/bin/phpunit
